---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  nodesecurity:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- node_modules/**/*
- tests/**/*
- gulpfile.babel.js
- coverage/**/*
- bin/*
- dist/**/*
- "*.json"
- "*.yml"
- ".*.yml"
- "*.md"
