language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
  - "4.2"
  - "5.2"
sudo: false
script: "gulp coverage"
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
cache:
    directories: 
        - ~/.npm
